#!/bin/bash
gallery_url=$1
LFS='/'

httblah() {
  curl "$gallery_url" | grep 'data-src' | cut -d \" -f10 > temp
  sed '/^$/d' temp > x
  sed 's/s.jpg/.jpg/' x > temp
  cat temp | while read line; do n=$((++n)) && curl $line >> "$n.jpg"; done 
  rm x temp
  return 0
}

if [ -n "$1" ]  #  If command-line argument present,
then

  if [ ${gallery_url:0:5} == "https" ]
  then
    echo "Converting https..."
    gallery_url=${gallery_url:8}
  elif [[ ${gallery_url:0:4} == "http" || ${gallery_url:0:5} == "imgur" ]]
  then
    echo "Using http..."
    setting=""
  else
    echo "Invalid entry"
    exit
  fi

  eval httblah

else
  echo -e "\nYou need to enter a parameter. Such as \nhttps://www.imgur.com/a/qwerty\n"
fi
